### ISSUE TITLE
Issue when using tools on Nukitashi

### ISSUE THREAD

**Issue by Alexeir-TL** [MishaIac/Shiina-Rio-TL-Tools#1]
Hi Mishalac, wanted to validate with you something that is happening with the S25 tool when using it for the nukitashi files that are inside of the .WAR files:

When unpacking the WAR files for the system images and such, there are a couple S25 files that have a lot of the images that i want to translate but when packing the file again i noticed that the file is considerably bigger than the original file, i didnt modify any image or anything at all, just unpacked and packed it:

![image](https://user-images.githubusercontent.com/131127177/232675260-9ab6177b-9897-43fd-850e-9192a4c5afb6.png)

and when packing it back into the WAR file and trying to opening the game, it is crashing with the following error:

![image](https://user-images.githubusercontent.com/131127177/232675528-330db19f-52ab-4c70-abb0-510e29b88cda.png)

Changing back to the original WAR fixes the game, but i wouldnt be able to translate a lot of the system messages and files if i cant change these images...

Do you know what could be happening here? Im not that good with programming so im not sure if there is something i can do on my side to fix this error.

**Comment by MishaIac** [comment]
Sorry, but these tools are not mine. I have compiled them here for my convenience, and have provided links to the original repositories. So please ask the author of this tool in the original repository.
Here is the link:
https://github.com/Yggdrasill-Moe/Niflheim/tree/master/RioShiina
